name: java_prod

services:
  backend:
    environment:
      - SPRING_PROFILE_ACTIVE=prod

  postgres:
    env_file:
      - .env.prod

  rabbitmq:
    env_file:
      - .env.prod
      
  nginx:
    ports:
      - 8002:80