CREATE TABLE IF NOT EXISTS faqs (
    id VARCHAR(255) PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    category VARCHAR(150),
    answer VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    message VARCHAR(255) NOT NULL
);