-- Add new columns to organisations table
ALTER TABLE organisations
ADD COLUMN slug VARCHAR(255) UNIQUE,
ADD COLUMN owner_id VARCHAR(255) REFERENCES users(id),
ADD COLUMN email VARCHAR(255),
ADD COLUMN industry VARCHAR(255),
ADD COLUMN type VARCHAR(255),
ADD COLUMN country VARCHAR(255),
ADD COLUMN address VARCHAR(255),
ADD COLUMN state VARCHAR(255),
ADD COLUMN created_at TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP;